---
title: '**Dispersion Theory**'
author: "Trevor Kapuvari, Nohman Akhtari"
date: "03/25/2024"
output:
  html_document:
    keep_md: yes
    toc: yes
    theme: sandstone
    toc_float: yes
    code_folding: hide
    number_sections: no
    css: style.css
  pdf_document:
    toc: yes
---
```{r setup, results = 'hide', message = FALSE, warning = FALSE, error = FALSE}
library(tidyverse)
library(tidycensus)
library(sf)
library(knitr)
library(viridis)
library(bookdown)
library(MASS)
library(rmarkdown)
options(scipen = 999)
knitr::opts_chunk$set(echo = TRUE)
theme_update(plot.title = element_text(hjust = 0.5))
```

# Introduction


# Methodology
For this assignment, we will use the Weighted Maximum Species Coverage Optimization Problem (MSCPW). We first give the mathematical formulation, and then delve into each term and an explanation:

$$
\text{max } \sum_{i \in I} w_iy_i \\
\text{s.t. } y_i - \sum_{j \in N_{i}} x_j \leq 0 \ \forall i\\
\sum_{j \in J} c_jx_j \leq \text{Budget} \\
x_j, y_i \in \{0,1\} \\
\text{where }\\
x_j = \begin{cases}1 & \text{, if we select parcel }j\\ 0 & \text{, otherwise} \end{cases}\\
y_i = \begin{cases}1 & \text{, if species } i \text{ is represented} \\ 0 & \text{, otherwise} \end{cases} \\
N_i \text{ is the set of parcels where species } i \text{has been observed} \\
w_j \text{ is the relative importance of species j} \\
c_j \text{ is the cost of a parcel}
$$
First, note that our objective is to maximize the weighted sum of distinct species represented To do this, we are constrained by the fact that for each species, we require a parcel $j$ in $N_i$ where we actually observed the species $i.$ This leads us to the first constraint. The second constraint puts a cap to the number of parcels we can select. This cap is set at the total cost, which is calculated by taking the cost of a parcel and multiplying it by 1 if the parcel ends up to be select. Our last constraint is the typical binary integer constraint.

The MSCP is quite intelligible, and the relevance of available space in this problem is especially clear. Nevertheless, this model is simplistic as it does not include considerations such as synergies between species or whether species could coexist in a parcel without major disturbance of the ecosystem.


# Code


# Conclusion


